dataset:
  name: amaai-lab/MusicBench
  split: test
  column: main_caption
model_name: small
device: cpu
ablation_layers: [16]
max_gen_num_tokens: 10
max_steps: 10
activation_buffer_size: 20
activation_batch_size: 10
text_batch_size: 10
warmup_steps: 1
top_k: 5
seed: 42
sae_size_multiplier: 1
