dataset:
  name: mszawerd/medium-sae-musicgen
  split: train
  column: main_caption
  local: False
model_name: medium
device: cuda
ablation_layers: [16]
max_steps: 12000
log_steps: 50
activation_batch_size: 20000
warmup_steps: 25
top_k: 32
seed: 42
sae_size_multiplier: 32