dataset:
  name: amaai-lab/MusicBench
  split: train
  column: main_caption
model_name: medium
device: cuda
ablation_layers: [16]
max_gen_num_tokens: 200
max_steps: 6000
log_steps: 300
activation_buffer_size: 6000
activation_batch_size: 1000
text_batch_size: 2
warmup_steps: 20
top_k: 32
seed: 42
sae_size_multiplier: 16