dataset:
  name: amaai-lab/MusicBench
  split: train
  column: main_caption
model_name: small
device: cuda
ablation_layers: [16]
max_gen_num_tokens: 255
max_steps: 10000000
activation_buffer_size: 2550
activation_batch_size: 100
text_batch_size: 10
warmup_steps: 1000
top_k: 5
seed: 42
sae_size_multiplier: 16
