dataset:
  name: amaai-lab/MusicBench
  split: test
  column: main_caption
model_name: small
device: cuda
batch_size: 10
music_per_prompt: 1
ablation_layers: [16]
max_gen_num_tokens: 255
max_steps: 1000
activation_buffer_size: 100
activation_batch_size: 10
warmup_steps: 10
top_k: 5
seed: 42
sae_size_multiplier: 16
