dataset:
  name: amaai-lab/MusicBench
  split: train
  column: main_caption
project_name: yue-sae
model_name: 7B-anneal-en-icl
device: cuda
ablation_layers: [15]
max_gen_num_tokens: 200
max_steps: 120000
log_steps: 300
activation_buffer_size: 6000
activation_batch_size: 1000
text_batch_size: 2
warmup_steps: 300
top_k: 32
seed: 42
sae_size_multiplier: 8