dataset:
  regex_name: "*"
  split: train
project_name: "sae-debug"
model_name: medium
device: cuda
ablation_layers: [16]
max_steps: 4000
log_steps: 100
activation_batch_size: 10000
warmup_steps: 300
top_k: 64
seed: 42
sae_size_multiplier: 4
lr: 0.0001