dataset:
  regex_name: "*"
  split: train
project_name: yue-sae
model_name: 7B-anneal-en-icl
device: cuda:1
ablation_layers: [15]
max_steps: 120000
log_steps: 300
save_steps: 900
activation_batch_size: 1000
warmup_steps: 300
top_k: 64
seed: 42
sae_size_multiplier: 3
lr: 0.0001