seed: 42
resample_sr: 16000
datasets:
  # - name: "music_bench_plugin"
  #   split: "train"
  #   max_rows: 60000
  #   postfix_path: "music-bench/datashare"
  #   separate_vocals_and_instruments: true
  - name: "song_describer_plugin"
    split: "train"
    max_pre_rows: 60000
    max_rows: 60000
    postfix_path: "song-describer/datashare"
    with_audio: True
    separate_vocals_and_instruments: true
model_name: "7B-anneal-en-icl"
device: "cuda:1"
layers: [15]
min_new_tokens: 3000
max_new_tokens: 3000
collect_batch_size: 1   # should be always be 1
max_examples_per_shard: 1000000
inference:
  top_p: 0.93
  temperature: 1.0
  repetition_penalty: 1.1
  guidance_scale: 1.5
processor:
  tokenizer_model: "./models/mm_tokenizer_v0.2_hf/tokenizer.model"
  codec_parent_path: "./dependencies"
  codec_config: "xcodec_mini_infer/final_ckpt/config.yaml"
  codec_resume: "xcodec_mini_infer/final_ckpt/ckpt_00360000.pth"