dataset:
  split: train
model_names: [small, medium]
activation_dims:
  - small: 1024
  - medium: 1536
device: cuda
ablation_layers: [16]
max_steps: 120000
log_steps: 300
save_steps: 1500
activation_batch_size: 10000
warmup_steps: 300
top_k: 32
seed: 42
sae_size_multiplier: 32
project_name: "musicgen-usae"