resample_sr: 32000
seed: 42
datasets:
  - name: "music_bench_plugin"
    split: "train"
    max_rows: 10
    postfix_path: "music-bench/datashare"
  - name: "song_describer_plugin"
    split: "train"
    max_pre_rows: 10
    max_rows: 15
    postfix_path: "song-describer"
    with_audio: True
  - name: "song_describer_plugin"
    split: "train"
    max_pre_rows: 10
    max_rows: 15
    postfix_path: "song-describer"
    with_audio: False
model_name: small
device: cuda
layers: [3]
max_gen_num_tokens: 20
collect_batch_size: 10
model_sampling_rate: 32000
max_examples_per_shard: 1000000
