resample_sr: 32000
seed: 42
datasets:
  - name: "music_bench_plugin"
    split: "train"
    max_rows: 60000
    postfix_path: "music-bench/datashare"
    separate_vocals_and_instruments: true
  - name: "song_describer_plugin"
    split: "train"
    max_pre_rows: 60000
    max_rows: 60000
    postfix_path: "song-describer/datashare"
    with_audio: True
    separate_vocals_and_instruments: true
model_name: medium
device: cuda:0
layers: [16]
max_gen_num_tokens: 500
collect_batch_size: 1
model_sampling_rate: 32000
max_examples_per_shard: 1000000
