resample_sr: 32000
seed: 42
datasets:
  - name: "jamendo_plugin"
    split: "train"
    max_pre_rows: 4000
    max_rows: 6000000000000
    postfix_path: "mtg-jamendo/datashare"
    with_audio: True
model_name: medium
device: cuda
layers: [16]
max_gen_num_tokens: 500
collect_batch_size: 1
model_sampling_rate: 32000
max_examples_per_shard: 1000000
